import type { Metadata } from 'next'
import { HeadeInstitutional } from '../components/Header/HeaderInstitutional'

export const metadata: Metadata = {
  title: 'GRProweb',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="w-full h-screen ">
        <HeadeInstitutional />
        {children}
      </body>
    </html>
  )
}
