import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'

import './globals.css'
import { Provider } from './components/ui/provider'
import App from 'next/app'
import AppProvider from './hooks'

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  
})

export const metadata: Metadata = {
  title: 'GRProweb',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true} className={roboto.className} >
      <body>
        <AppProvider>
          <Provider>{children}</Provider>
        </AppProvider>
      </body>
    </html>
  )
}
