'use cleint'
import type { Metadata } from 'next'
import { HeadeClient } from '../components/Header/HeaderClient'
import Sidebar from '../components/ClientArea/Sidebar/Sidebar'

export const metadata: Metadata = {
  title: 'GRProweb',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
        <div className="">
          <HeadeClient />
          <main className="grid grid-cols-app bg-slate-100">
            <Sidebar />
            <div className="min-h-screen border-t-2 w-full">{children}</div>
          </main>
        </div>
  )
}
